displayName=Public Chat And NPC Overhead Chat Remover
author=Toll
description="Removes Selected Automatic Public Chat Entries and NPC Overhead Chat Messages"
tags=overhead,chat,text,message,public,message,dragon,axe,harpoon,pickaxe,cerberus,nex,barbarian,rogue,rogues,summoned,soul,gwd,bandos,godwars,god wars, graardor, zilyana, kril, kree, chop, chop chop, fishy, fishies, smashing
plugins=com.PublicChatAndNPCOverheadRemover.PublicChatAndNPCOverheadRemoverPlugin
